"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

@Author: AlfredNG
@Date: 2024-02-03 10:43:06
@Description:
@Copyright: Copyright (c) 2024-Present AVCIT
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class CommRes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    code: builtins.int
    msg: builtins.str
    def __init__(
        self,
        *,
        code: builtins.int = ...,
        msg: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code", b"code", "msg", b"msg"]) -> None: ...

global___CommRes = CommRes

@typing_extensions.final
class Point(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.int
    y: builtins.int
    def __init__(
        self,
        *,
        x: builtins.int = ...,
        y: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["x", b"x", "y", b"y"]) -> None: ...

global___Point = Point

@typing_extensions.final
class Line(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    X1_FIELD_NUMBER: builtins.int
    Y1_FIELD_NUMBER: builtins.int
    X2_FIELD_NUMBER: builtins.int
    Y2_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    x1: builtins.int
    y1: builtins.int
    x2: builtins.int
    y2: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
        x1: builtins.int = ...,
        y1: builtins.int = ...,
        x2: builtins.int = ...,
        y2: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name", "x1", b"x1", "x2", b"x2", "y1", b"y1", "y2", b"y2"]) -> None: ...

global___Line = Line

@typing_extensions.final
class Area(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    POINTS_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    @property
    def points(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Point]: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
        points: collections.abc.Iterable[global___Point] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name", "points", b"points"]) -> None: ...

global___Area = Area
