# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/global.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/global.proto\x12\x05proto\"$\n\x07\x43ommRes\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\"P\n\x04Line\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02x1\x18\x03 \x01(\r\x12\n\n\x02y1\x18\x04 \x01(\r\x12\n\n\x02x2\x18\x05 \x01(\r\x12\n\n\x02y2\x18\x06 \x01(\r\">\n\x04\x41rea\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1c\n\x06points\x18\x03 \x03(\x0b\x32\x0c.proto.PointB\rZ\x0b./proto/algb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.global_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./proto/alg'
  _globals['_COMMRES']._serialized_start=29
  _globals['_COMMRES']._serialized_end=65
  _globals['_POINT']._serialized_start=67
  _globals['_POINT']._serialized_end=96
  _globals['_LINE']._serialized_start=98
  _globals['_LINE']._serialized_end=178
  _globals['_AREA']._serialized_start=180
  _globals['_AREA']._serialized_end=242
# @@protoc_insertion_point(module_scope)
