"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

@Author: AlfredNG
@Date: 2024-02-03 10:43:06
@Description:
@Copyright: Copyright (c) 2024-Present AVCIT
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import proto.global_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PICTURE_TYPE:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PICTURE_TYPEEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PICTURE_TYPE.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PICTURE_TYPE_UNKNOWN: _PICTURE_TYPE.ValueType  # 0
    PICTURE_TYPE_FACE: _PICTURE_TYPE.ValueType  # 1
    PICTURE_TYPE_PERSON: _PICTURE_TYPE.ValueType  # 2
    PICTURE_TYPE_NON_VEHICLE: _PICTURE_TYPE.ValueType  # 3
    PICTURE_TYPE_VEHICLE: _PICTURE_TYPE.ValueType  # 4

class PICTURE_TYPE(_PICTURE_TYPE, metaclass=_PICTURE_TYPEEnumTypeWrapper): ...

PICTURE_TYPE_UNKNOWN: PICTURE_TYPE.ValueType  # 0
PICTURE_TYPE_FACE: PICTURE_TYPE.ValueType  # 1
PICTURE_TYPE_PERSON: PICTURE_TYPE.ValueType  # 2
PICTURE_TYPE_NON_VEHICLE: PICTURE_TYPE.ValueType  # 3
PICTURE_TYPE_VEHICLE: PICTURE_TYPE.ValueType  # 4
global___PICTURE_TYPE = PICTURE_TYPE

@typing_extensions.final
class Channel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    url: builtins.str
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
        url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name", "url", b"url"]) -> None: ...

global___Channel = Channel

@typing_extensions.final
class Picture(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    SRCDATA_FIELD_NUMBER: builtins.int
    ROIDATA_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    id: builtins.int
    srcData: builtins.bytes
    """jpg图片"""
    roiData: builtins.bytes
    """jpg图片"""
    type: global___PICTURE_TYPE.ValueType
    """图片类型"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        srcData: builtins.bytes = ...,
        roiData: builtins.bytes = ...,
        type: global___PICTURE_TYPE.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "roiData", b"roiData", "srcData", b"srcData", "type", b"type"]) -> None: ...

global___Picture = Picture

@typing_extensions.final
class TaskReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ROOT_PATH_FIELD_NUMBER: builtins.int
    MODEL_PATH_FIELD_NUMBER: builtins.int
    id: builtins.int
    type: builtins.int
    """任务类型"""
    name: builtins.str
    """任务名称"""
    root_path: builtins.str
    """任务根目录"""
    @property
    def model_path(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """模型路径"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        type: builtins.int = ...,
        name: builtins.str = ...,
        root_path: builtins.str = ...,
        model_path: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "model_path", b"model_path", "name", b"name", "root_path", b"root_path", "type", b"type"]) -> None: ...

global___TaskReq = TaskReq

@typing_extensions.final
class CounterVehicleCatogory(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    SUM_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    sum: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
        sum: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name", "sum", b"sum"]) -> None: ...

global___CounterVehicleCatogory = CounterVehicleCatogory

@typing_extensions.final
class CounterVehicleLine(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LINE_FIELD_NUMBER: builtins.int
    COUNTERS_FIELD_NUMBER: builtins.int
    @property
    def line(self) -> proto.global_pb2.Line: ...
    @property
    def counters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CounterVehicleCatogory]:
        """属性统计"""
    def __init__(
        self,
        *,
        line: proto.global_pb2.Line | None = ...,
        counters: collections.abc.Iterable[global___CounterVehicleCatogory] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["line", b"line"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["counters", b"counters", "line", b"line"]) -> None: ...

global___CounterVehicleLine = CounterVehicleLine

@typing_extensions.final
class CounterVehicleArea(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AREA_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    @property
    def area(self) -> proto.global_pb2.Area: ...
    state: builtins.int
    """区域拥堵情况"""
    def __init__(
        self,
        *,
        area: proto.global_pb2.Area | None = ...,
        state: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["area", b"area"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["area", b"area", "state", b"state"]) -> None: ...

global___CounterVehicleArea = CounterVehicleArea

@typing_extensions.final
class CounterVehicleNotify(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_FIELD_NUMBER: builtins.int
    LINES_FIELD_NUMBER: builtins.int
    AREAS_FIELD_NUMBER: builtins.int
    @property
    def channel(self) -> global___Channel: ...
    @property
    def lines(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CounterVehicleLine]: ...
    @property
    def areas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CounterVehicleArea]: ...
    def __init__(
        self,
        *,
        channel: global___Channel | None = ...,
        lines: collections.abc.Iterable[global___CounterVehicleLine] | None = ...,
        areas: collections.abc.Iterable[global___CounterVehicleArea] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["channel", b"channel"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["areas", b"areas", "channel", b"channel", "lines", b"lines"]) -> None: ...

global___CounterVehicleNotify = CounterVehicleNotify

@typing_extensions.final
class CollectNotify(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_FIELD_NUMBER: builtins.int
    PICTURE_FIELD_NUMBER: builtins.int
    @property
    def channel(self) -> global___Channel: ...
    @property
    def picture(self) -> global___Picture: ...
    def __init__(
        self,
        *,
        channel: global___Channel | None = ...,
        picture: global___Picture | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["channel", b"channel", "picture", b"picture"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["channel", b"channel", "picture", b"picture"]) -> None: ...

global___CollectNotify = CollectNotify

@typing_extensions.final
class CollectAlg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_FIELD_NUMBER: builtins.int
    @property
    def channel(self) -> global___Channel: ...
    def __init__(
        self,
        *,
        channel: global___Channel | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["channel", b"channel"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["channel", b"channel"]) -> None: ...

global___CollectAlg = CollectAlg

@typing_extensions.final
class CounterVehicleAlg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_FIELD_NUMBER: builtins.int
    LINES_FIELD_NUMBER: builtins.int
    AREAS_FIELD_NUMBER: builtins.int
    @property
    def channel(self) -> global___Channel: ...
    @property
    def lines(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[proto.global_pb2.Line]: ...
    @property
    def areas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[proto.global_pb2.Area]: ...
    def __init__(
        self,
        *,
        channel: global___Channel | None = ...,
        lines: collections.abc.Iterable[proto.global_pb2.Line] | None = ...,
        areas: collections.abc.Iterable[proto.global_pb2.Area] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["channel", b"channel"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["areas", b"areas", "channel", b"channel", "lines", b"lines"]) -> None: ...

global___CounterVehicleAlg = CounterVehicleAlg

@typing_extensions.final
class AlgConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COUNTER_VEHICLE_ALG_FIELD_NUMBER: builtins.int
    COLLECT_ALG_FIELD_NUMBER: builtins.int
    @property
    def counter_vehicle_alg(self) -> global___CounterVehicleAlg: ...
    @property
    def collect_alg(self) -> global___CollectAlg: ...
    def __init__(
        self,
        *,
        counter_vehicle_alg: global___CounterVehicleAlg | None = ...,
        collect_alg: global___CollectAlg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["alg", b"alg", "collect_alg", b"collect_alg", "counter_vehicle_alg", b"counter_vehicle_alg"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["alg", b"alg", "collect_alg", b"collect_alg", "counter_vehicle_alg", b"counter_vehicle_alg"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["alg", b"alg"]) -> typing_extensions.Literal["counter_vehicle_alg", "collect_alg"] | None: ...

global___AlgConfig = AlgConfig

@typing_extensions.final
class TaskNotify(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COUNTER_VEHICLE_NOTIFY_FIELD_NUMBER: builtins.int
    COLLECT_NOTIFY_FIELD_NUMBER: builtins.int
    @property
    def counter_vehicle_notify(self) -> global___CounterVehicleNotify: ...
    @property
    def collect_notify(self) -> global___CollectNotify: ...
    def __init__(
        self,
        *,
        counter_vehicle_notify: global___CounterVehicleNotify | None = ...,
        collect_notify: global___CollectNotify | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["collect_notify", b"collect_notify", "counter_vehicle_notify", b"counter_vehicle_notify", "task_notify", b"task_notify"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["collect_notify", b"collect_notify", "counter_vehicle_notify", b"counter_vehicle_notify", "task_notify", b"task_notify"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["task_notify", b"task_notify"]) -> typing_extensions.Literal["counter_vehicle_notify", "collect_notify"] | None: ...

global___TaskNotify = TaskNotify

@typing_extensions.final
class RunningState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNELS_FIELD_NUMBER: builtins.int
    @property
    def channels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Channel]:
        """所有运行通道"""
    def __init__(
        self,
        *,
        channels: collections.abc.Iterable[global___Channel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channels", b"channels"]) -> None: ...

global___RunningState = RunningState
