# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/alg_core/common.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/alg_core/common.proto\x12\x08\x61lg_core\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\"\'\n\x04\x41rea\x12\x1f\n\x06points\x18\x01 \x03(\x0b\x32\x0f.alg_core.Point\"E\n\tRectangle\x12\x0c\n\x04left\x18\x01 \x01(\x05\x12\x0b\n\x03top\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"5\n\x03\x42ox\x12\n\n\x02x1\x18\x01 \x01(\x05\x12\n\n\x02y1\x18\x02 \x01(\x05\x12\n\n\x02x2\x18\x03 \x01(\x05\x12\n\n\x02y2\x18\x04 \x01(\x05\"c\n\tMediaInfo\x12\x12\n\nchannel_id\x18\x01 \x01(\x03\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12#\n\x05\x63odec\x18\x04 \x01(\x0e\x32\x14.alg_core.MediaCodec*N\n\nMediaCodec\x12\x10\n\x0c\x43ODEC_UNKNOW\x10\x00\x12\x0e\n\nCODEC_JPEG\x10\x01\x12\x0e\n\nCODEC_H264\x10\x02\x12\x0e\n\nCODEC_H265\x10\x03\x42\x11Z\x0f./proto/algcoreb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.alg_core.common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./proto/algcore'
  _globals['_MEDIACODEC']._serialized_start=340
  _globals['_MEDIACODEC']._serialized_end=418
  _globals['_POINT']._serialized_start=41
  _globals['_POINT']._serialized_end=70
  _globals['_AREA']._serialized_start=72
  _globals['_AREA']._serialized_end=111
  _globals['_RECTANGLE']._serialized_start=113
  _globals['_RECTANGLE']._serialized_end=182
  _globals['_BOX']._serialized_start=184
  _globals['_BOX']._serialized_end=237
  _globals['_MEDIAINFO']._serialized_start=239
  _globals['_MEDIAINFO']._serialized_end=338
# @@protoc_insertion_point(module_scope)
