"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

@Author: AlfredNG
@Date: 2024-02-03 10:43:06
@Description:
@Copyright: Copyright (c) 2024-Present AVCIT
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MediaCodec:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MediaCodecEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MediaCodec.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CODEC_UNKNOW: _MediaCodec.ValueType  # 0
    CODEC_JPEG: _MediaCodec.ValueType  # 1
    CODEC_H264: _MediaCodec.ValueType  # 2
    CODEC_H265: _MediaCodec.ValueType  # 3

class MediaCodec(_MediaCodec, metaclass=_MediaCodecEnumTypeWrapper): ...

CODEC_UNKNOW: MediaCodec.ValueType  # 0
CODEC_JPEG: MediaCodec.ValueType  # 1
CODEC_H264: MediaCodec.ValueType  # 2
CODEC_H265: MediaCodec.ValueType  # 3
global___MediaCodec = MediaCodec

@typing_extensions.final
class Point(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.int
    """百分比"""
    y: builtins.int
    """百分比"""
    def __init__(
        self,
        *,
        x: builtins.int = ...,
        y: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["x", b"x", "y", b"y"]) -> None: ...

global___Point = Point

@typing_extensions.final
class Area(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POINTS_FIELD_NUMBER: builtins.int
    @property
    def points(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Point]: ...
    def __init__(
        self,
        *,
        points: collections.abc.Iterable[global___Point] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["points", b"points"]) -> None: ...

global___Area = Area

@typing_extensions.final
class Rectangle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEFT_FIELD_NUMBER: builtins.int
    TOP_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    left: builtins.int
    top: builtins.int
    width: builtins.int
    height: builtins.int
    def __init__(
        self,
        *,
        left: builtins.int = ...,
        top: builtins.int = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["height", b"height", "left", b"left", "top", b"top", "width", b"width"]) -> None: ...

global___Rectangle = Rectangle

@typing_extensions.final
class Box(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X1_FIELD_NUMBER: builtins.int
    Y1_FIELD_NUMBER: builtins.int
    X2_FIELD_NUMBER: builtins.int
    Y2_FIELD_NUMBER: builtins.int
    x1: builtins.int
    y1: builtins.int
    x2: builtins.int
    y2: builtins.int
    def __init__(
        self,
        *,
        x1: builtins.int = ...,
        y1: builtins.int = ...,
        x2: builtins.int = ...,
        y2: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["x1", b"x1", "x2", b"x2", "y1", b"y1", "y2", b"y2"]) -> None: ...

global___Box = Box

@typing_extensions.final
class MediaInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_ID_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    CODEC_FIELD_NUMBER: builtins.int
    channel_id: builtins.int
    width: builtins.int
    height: builtins.int
    codec: global___MediaCodec.ValueType
    def __init__(
        self,
        *,
        channel_id: builtins.int = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
        codec: global___MediaCodec.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channel_id", b"channel_id", "codec", b"codec", "height", b"height", "width", b"width"]) -> None: ...

global___MediaInfo = MediaInfo
