# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.alg_core import common_pb2 as proto_dot_alg__core_dot_common__pb2
from proto.alg_core import core_pb2 as proto_dot_alg__core_dot_core__pb2


class CoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTask = channel.unary_unary(
                '/alg_core.CoreService/AddTask',
                request_serializer=proto_dot_alg__core_dot_core__pb2.AddTaskReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RemoveTask = channel.unary_unary(
                '/alg_core.CoreService/RemoveTask',
                request_serializer=proto_dot_alg__core_dot_core__pb2.RemoveTaskReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.EnableChannel = channel.unary_unary(
                '/alg_core.CoreService/EnableChannel',
                request_serializer=proto_dot_alg__core_dot_core__pb2.EnableChannelReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DisableChannel = channel.unary_unary(
                '/alg_core.CoreService/DisableChannel',
                request_serializer=proto_dot_alg__core_dot_core__pb2.DisableChannelReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.BindChanTask = channel.unary_unary(
                '/alg_core.CoreService/BindChanTask',
                request_serializer=proto_dot_alg__core_dot_core__pb2.BindChanTaskReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UnbindChanTask = channel.unary_unary(
                '/alg_core.CoreService/UnbindChanTask',
                request_serializer=proto_dot_alg__core_dot_core__pb2.DisableChannelReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.PublishMediaInfo = channel.unary_unary(
                '/alg_core.CoreService/PublishMediaInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_alg__core_dot_common__pb2.MediaInfo.FromString,
                )
        self.GetMediaInfo = channel.unary_unary(
                '/alg_core.CoreService/GetMediaInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_alg__core_dot_common__pb2.MediaInfo.FromString,
                )
        self.PublishEvent = channel.unary_unary(
                '/alg_core.CoreService/PublishEvent',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_alg__core_dot_core__pb2.Event.FromString,
                )


class CoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTask(self, request, context):
        """添加任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTask(self, request, context):
        """移除任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableChannel(self, request, context):
        """使能通道
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableChannel(self, request, context):
        """关闭通道
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BindChanTask(self, request, context):
        """绑定通道和任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnbindChanTask(self, request, context):
        """解绑通道和任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishMediaInfo(self, request, context):
        """有改变主动提交流媒体信息到上层
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMediaInfo(self, request, context):
        """上层主动获取流媒体信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTask,
                    request_deserializer=proto_dot_alg__core_dot_core__pb2.AddTaskReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTask,
                    request_deserializer=proto_dot_alg__core_dot_core__pb2.RemoveTaskReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'EnableChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableChannel,
                    request_deserializer=proto_dot_alg__core_dot_core__pb2.EnableChannelReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DisableChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableChannel,
                    request_deserializer=proto_dot_alg__core_dot_core__pb2.DisableChannelReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'BindChanTask': grpc.unary_unary_rpc_method_handler(
                    servicer.BindChanTask,
                    request_deserializer=proto_dot_alg__core_dot_core__pb2.BindChanTaskReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UnbindChanTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UnbindChanTask,
                    request_deserializer=proto_dot_alg__core_dot_core__pb2.DisableChannelReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'PublishMediaInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishMediaInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_alg__core_dot_common__pb2.MediaInfo.SerializeToString,
            ),
            'GetMediaInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMediaInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_alg__core_dot_common__pb2.MediaInfo.SerializeToString,
            ),
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_alg__core_dot_core__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alg_core.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alg_core.CoreService/AddTask',
            proto_dot_alg__core_dot_core__pb2.AddTaskReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alg_core.CoreService/RemoveTask',
            proto_dot_alg__core_dot_core__pb2.RemoveTaskReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnableChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alg_core.CoreService/EnableChannel',
            proto_dot_alg__core_dot_core__pb2.EnableChannelReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisableChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alg_core.CoreService/DisableChannel',
            proto_dot_alg__core_dot_core__pb2.DisableChannelReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BindChanTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alg_core.CoreService/BindChanTask',
            proto_dot_alg__core_dot_core__pb2.BindChanTaskReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnbindChanTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alg_core.CoreService/UnbindChanTask',
            proto_dot_alg__core_dot_core__pb2.DisableChannelReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PublishMediaInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alg_core.CoreService/PublishMediaInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_alg__core_dot_common__pb2.MediaInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMediaInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alg_core.CoreService/GetMediaInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_alg__core_dot_common__pb2.MediaInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alg_core.CoreService/PublishEvent',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_alg__core_dot_core__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
