"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

@Author: AlfredNG
@Date: 2024-02-03 10:43:06
@Description: about the alg channel api
@Copyright: Copyright (c) 2024-Present AVCIT
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import proto.alg_core.common_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ServiceType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ServiceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ServiceType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SERVICE_TYPE_NONE: _ServiceType.ValueType  # 0
    SERVICE_TYPE_SMART_SITE_CAR_COVER: _ServiceType.ValueType  # 1
    SERVICE_TYPE_SMART_SITE_CAR_WHEEL: _ServiceType.ValueType  # 2
    SERVICE_TYPE_SMART_SITE_CAR_LINCESE_PLATE: _ServiceType.ValueType  # 3
    SERVICE_TYPE_SMART_SITE_PERSON_HELMET: _ServiceType.ValueType  # 4
    """! safety helmet"""
    SERVICE_TYPE_SMART_SITE_PERSON_REFLECTIVE: _ServiceType.ValueType  # 5
    """! reflective vest"""
    SERVICE_TYPE_SAMRT_SITE_PERSON_SMOKING: _ServiceType.ValueType  # 6
    SERVICE_TYPE_SMART_SITE_ENV_BARE_SOIL: _ServiceType.ValueType  # 7
    SERVICE_TYPE_SMART_SITE_ENV_SMOKE: _ServiceType.ValueType  # 8
    SERVICE_TYPE_SMART_SITE_ENV_FLAME: _ServiceType.ValueType  # 9
    SERVICE_TYPE_SMART_SITE_PERSON_NIGHT: _ServiceType.ValueType  # 10
    SERVICE_TYPE_OBJCNT: _ServiceType.ValueType  # 11
    """object count"""
    SERVICE_TYPE_OBJCAP: _ServiceType.ValueType  # 12
    """object capture"""
    SERVICE_TYPE_PERSON_OBJCAP: _ServiceType.ValueType  # 13
    SERVICE_TYPE_CAR_OBJCAP: _ServiceType.ValueType  # 14
    SERVICE_TYPE_NONCAR_OBJCAP: _ServiceType.ValueType  # 15
    SERVICE_TYPE_FACERECOGNITION: _ServiceType.ValueType  # 16
    """face recognition"""
    SERVICE_TYPE_ELECINTRU: _ServiceType.ValueType  # 17
    """electric bike intrusion"""
    SERVICE_TYPE_WALKDOGDET: _ServiceType.ValueType  # 18
    """walk dog without people"""
    SERVICE_TYPE_PERSON_WANDER: _ServiceType.ValueType  # 19
    """person wander"""
    SERVICE_TYPE_PARK_RIDE_DET: _ServiceType.ValueType  # 20
    """park ride detection"""
    SERVICE_TYPE_NONCAR_OCCUPY: _ServiceType.ValueType  # 21
    """non-car occupancy"""
    SERVICE_TYPE_SHIP_OBJCAP: _ServiceType.ValueType  # 22
    """ship object capture"""
    SERVICE_TYPE_CROWD_DET: _ServiceType.ValueType  # 23
    """crown detection"""
    SERVICE_TYPE_FALLDOWN_DET: _ServiceType.ValueType  # 24
    """fall down detection"""
    SERVICE_TYPE_RUBBISH_HEAP_DET: _ServiceType.ValueType  # 25
    """rubbish heap detection"""
    SERVICE_TYPE_RUBBISH_OVERFLOW_DET: _ServiceType.ValueType  # 26
    """rubbish overflow detection"""
    SERVICE_TYPE_SMOKE_DET: _ServiceType.ValueType  # 27
    """smoke detection"""
    SERVICE_TYPE_FIRE_DET: _ServiceType.ValueType  # 28
    """fire detection"""

class ServiceType(_ServiceType, metaclass=_ServiceTypeEnumTypeWrapper): ...

SERVICE_TYPE_NONE: ServiceType.ValueType  # 0
SERVICE_TYPE_SMART_SITE_CAR_COVER: ServiceType.ValueType  # 1
SERVICE_TYPE_SMART_SITE_CAR_WHEEL: ServiceType.ValueType  # 2
SERVICE_TYPE_SMART_SITE_CAR_LINCESE_PLATE: ServiceType.ValueType  # 3
SERVICE_TYPE_SMART_SITE_PERSON_HELMET: ServiceType.ValueType  # 4
"""! safety helmet"""
SERVICE_TYPE_SMART_SITE_PERSON_REFLECTIVE: ServiceType.ValueType  # 5
"""! reflective vest"""
SERVICE_TYPE_SAMRT_SITE_PERSON_SMOKING: ServiceType.ValueType  # 6
SERVICE_TYPE_SMART_SITE_ENV_BARE_SOIL: ServiceType.ValueType  # 7
SERVICE_TYPE_SMART_SITE_ENV_SMOKE: ServiceType.ValueType  # 8
SERVICE_TYPE_SMART_SITE_ENV_FLAME: ServiceType.ValueType  # 9
SERVICE_TYPE_SMART_SITE_PERSON_NIGHT: ServiceType.ValueType  # 10
SERVICE_TYPE_OBJCNT: ServiceType.ValueType  # 11
"""object count"""
SERVICE_TYPE_OBJCAP: ServiceType.ValueType  # 12
"""object capture"""
SERVICE_TYPE_PERSON_OBJCAP: ServiceType.ValueType  # 13
SERVICE_TYPE_CAR_OBJCAP: ServiceType.ValueType  # 14
SERVICE_TYPE_NONCAR_OBJCAP: ServiceType.ValueType  # 15
SERVICE_TYPE_FACERECOGNITION: ServiceType.ValueType  # 16
"""face recognition"""
SERVICE_TYPE_ELECINTRU: ServiceType.ValueType  # 17
"""electric bike intrusion"""
SERVICE_TYPE_WALKDOGDET: ServiceType.ValueType  # 18
"""walk dog without people"""
SERVICE_TYPE_PERSON_WANDER: ServiceType.ValueType  # 19
"""person wander"""
SERVICE_TYPE_PARK_RIDE_DET: ServiceType.ValueType  # 20
"""park ride detection"""
SERVICE_TYPE_NONCAR_OCCUPY: ServiceType.ValueType  # 21
"""non-car occupancy"""
SERVICE_TYPE_SHIP_OBJCAP: ServiceType.ValueType  # 22
"""ship object capture"""
SERVICE_TYPE_CROWD_DET: ServiceType.ValueType  # 23
"""crown detection"""
SERVICE_TYPE_FALLDOWN_DET: ServiceType.ValueType  # 24
"""fall down detection"""
SERVICE_TYPE_RUBBISH_HEAP_DET: ServiceType.ValueType  # 25
"""rubbish heap detection"""
SERVICE_TYPE_RUBBISH_OVERFLOW_DET: ServiceType.ValueType  # 26
"""rubbish overflow detection"""
SERVICE_TYPE_SMOKE_DET: ServiceType.ValueType  # 27
"""smoke detection"""
SERVICE_TYPE_FIRE_DET: ServiceType.ValueType  # 28
"""fire detection"""
global___ServiceType = ServiceType

class _EventType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EventTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EventType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    EVENT_TYPE_ALARM: _EventType.ValueType  # 0
    """! smart site"""
    EVENT_TYPE_OBJECT_COUNT: _EventType.ValueType  # 1
    """! object flow statistics"""
    EVENT_TYPE_OBJECT_CAPTURE: _EventType.ValueType  # 2
    """! object capture"""
    EVENT_TYPE_OBJECT_DETECT: _EventType.ValueType  # 3
    """! object count"""
    EVENT_TYPE_ELEC_INTR_LAD: _EventType.ValueType  # 4
    """! electric-bike intrude elevator"""
    EVENT_TYPE_WALK_DOG_DET: _EventType.ValueType  # 5
    """! walk dog without owner near by"""
    EVENT_TYPE_FACE_RECOGNITION: _EventType.ValueType  # 6
    """! face recognition service"""
    EVENT_TYPE_SHIP_CAPTURE: _EventType.ValueType  # 7
    """! ship capture"""
    EVENT_TYPE_NONCAR_OCCUPY_CAP: _EventType.ValueType  # 8
    """! non-car occupy capture"""
    EVENT_TYPE_RUBISH_HEAP_DET_CAP: _EventType.ValueType  # 9
    """! rubbish heap detection capture"""
    EVENT_TYPE_RUBISH_OVER_FLOW_DET_CAP: _EventType.ValueType  # 10
    """! rubbish overflow detection capture"""
    EVENT_TYPE_FALL_DOWN_DET_CAP: _EventType.ValueType  # 11
    """! fall down detection capture"""
    EVENT_TYPE_SMOKE_FIRE_DET_CAP: _EventType.ValueType  # 12
    """! smoke fire detection capture"""
    EVENT_TYPE_CROWN_DET_CAP: _EventType.ValueType  # 13
    """! crown detection capture"""
    EVENT_TYPE_SIT_PERSON_SMOKING_CAP: _EventType.ValueType  # 14
    """! site person smoking capture"""
    EVENT_TYPE_PERSON_WANDER: _EventType.ValueType  # 15
    """! person wander"""
    EVENT_TYPE_PARK_RIDE: _EventType.ValueType  # 16
    """! park ride"""

class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper): ...

EVENT_TYPE_ALARM: EventType.ValueType  # 0
"""! smart site"""
EVENT_TYPE_OBJECT_COUNT: EventType.ValueType  # 1
"""! object flow statistics"""
EVENT_TYPE_OBJECT_CAPTURE: EventType.ValueType  # 2
"""! object capture"""
EVENT_TYPE_OBJECT_DETECT: EventType.ValueType  # 3
"""! object count"""
EVENT_TYPE_ELEC_INTR_LAD: EventType.ValueType  # 4
"""! electric-bike intrude elevator"""
EVENT_TYPE_WALK_DOG_DET: EventType.ValueType  # 5
"""! walk dog without owner near by"""
EVENT_TYPE_FACE_RECOGNITION: EventType.ValueType  # 6
"""! face recognition service"""
EVENT_TYPE_SHIP_CAPTURE: EventType.ValueType  # 7
"""! ship capture"""
EVENT_TYPE_NONCAR_OCCUPY_CAP: EventType.ValueType  # 8
"""! non-car occupy capture"""
EVENT_TYPE_RUBISH_HEAP_DET_CAP: EventType.ValueType  # 9
"""! rubbish heap detection capture"""
EVENT_TYPE_RUBISH_OVER_FLOW_DET_CAP: EventType.ValueType  # 10
"""! rubbish overflow detection capture"""
EVENT_TYPE_FALL_DOWN_DET_CAP: EventType.ValueType  # 11
"""! fall down detection capture"""
EVENT_TYPE_SMOKE_FIRE_DET_CAP: EventType.ValueType  # 12
"""! smoke fire detection capture"""
EVENT_TYPE_CROWN_DET_CAP: EventType.ValueType  # 13
"""! crown detection capture"""
EVENT_TYPE_SIT_PERSON_SMOKING_CAP: EventType.ValueType  # 14
"""! site person smoking capture"""
EVENT_TYPE_PERSON_WANDER: EventType.ValueType  # 15
"""! person wander"""
EVENT_TYPE_PARK_RIDE: EventType.ValueType  # 16
"""! park ride"""
global___EventType = EventType

@typing_extensions.final
class AddTaskReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICE_ID_FIELD_NUMBER: builtins.int
    DEV_ID_FIELD_NUMBER: builtins.int
    ROOT_FIELD_NUMBER: builtins.int
    MODEL_FILES_FIELD_NUMBER: builtins.int
    service_id: builtins.int
    dev_id: builtins.int
    """显卡ID"""
    root: builtins.str
    """工作目录"""
    @property
    def model_files(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """模型路径"""
    def __init__(
        self,
        *,
        service_id: builtins.int = ...,
        dev_id: builtins.int = ...,
        root: builtins.str = ...,
        model_files: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["dev_id", b"dev_id", "model_files", b"model_files", "root", b"root", "service_id", b"service_id"]) -> None: ...

global___AddTaskReq = AddTaskReq

@typing_extensions.final
class RemoveTaskReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICE_ID_FIELD_NUMBER: builtins.int
    service_id: builtins.int
    def __init__(
        self,
        *,
        service_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["service_id", b"service_id"]) -> None: ...

global___RemoveTaskReq = RemoveTaskReq

@typing_extensions.final
class EnableChannelReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_ID_FIELD_NUMBER: builtins.int
    CHANNEL_NAME_FIELD_NUMBER: builtins.int
    CHANNEL_URL_FIELD_NUMBER: builtins.int
    channel_id: builtins.int
    channel_name: builtins.str
    channel_url: builtins.str
    def __init__(
        self,
        *,
        channel_id: builtins.int = ...,
        channel_name: builtins.str = ...,
        channel_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channel_id", b"channel_id", "channel_name", b"channel_name", "channel_url", b"channel_url"]) -> None: ...

global___EnableChannelReq = EnableChannelReq

@typing_extensions.final
class DisableChannelReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_ID_FIELD_NUMBER: builtins.int
    channel_id: builtins.int
    def __init__(
        self,
        *,
        channel_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channel_id", b"channel_id"]) -> None: ...

global___DisableChannelReq = DisableChannelReq

@typing_extensions.final
class ChanServiceConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_TYPE_FIELD_NUMBER: builtins.int
    ROI_FIELD_NUMBER: builtins.int
    BOX_MIN_W_FIELD_NUMBER: builtins.int
    BOX_MIN_H_FIELD_NUMBER: builtins.int
    DET_THRESHOLD_FIELD_NUMBER: builtins.int
    MATCH_THRESHOLD_FIELD_NUMBER: builtins.int
    ALARM_INTERVAL_FIELD_NUMBER: builtins.int
    PGIE_INTEVAL_FIELD_NUMBER: builtins.int
    WINDOW_LEN_FIELD_NUMBER: builtins.int
    WINDOW_HIT_FIELD_NUMBER: builtins.int
    CROWD_NUM_THRESHOLD_FIELD_NUMBER: builtins.int
    FACEQA_THRESHOLD_FIELD_NUMBER: builtins.int
    task_type: global___ServiceType.ValueType
    """任务类型"""
    @property
    def roi(self) -> proto.alg_core.common_pb2.Area:
        """roi config"""
    box_min_w: builtins.int
    """目标框最小宽度"""
    box_min_h: builtins.int
    """目标框最小高度"""
    det_threshold: builtins.float
    """检测阈值"""
    match_threshold: builtins.float
    """比对阈值"""
    alarm_interval: builtins.int
    """报警间隔, 上报一次后, 间隔alarmInterval秒后,"""
    pgie_inteval: builtins.int
    """才可以继续根据判断条件上报
    推理间隔, 每隔pgieInteval秒, 推理一次
    """
    window_len: builtins.int
    """告警长度"""
    window_hit: builtins.int
    """告警灵敏   winLen=5; winHit=2; 说明: 5次推理后,"""
    crowd_num_threshold: builtins.int
    """其中3次满足告警条件, 则触发告警

    人群聚集数量阈值
    """
    faceqa_threshold: builtins.float
    """人脸质量阈值"""
    def __init__(
        self,
        *,
        task_type: global___ServiceType.ValueType = ...,
        roi: proto.alg_core.common_pb2.Area | None = ...,
        box_min_w: builtins.int = ...,
        box_min_h: builtins.int = ...,
        det_threshold: builtins.float = ...,
        match_threshold: builtins.float = ...,
        alarm_interval: builtins.int = ...,
        pgie_inteval: builtins.int = ...,
        window_len: builtins.int = ...,
        window_hit: builtins.int = ...,
        crowd_num_threshold: builtins.int = ...,
        faceqa_threshold: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["roi", b"roi"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["alarm_interval", b"alarm_interval", "box_min_h", b"box_min_h", "box_min_w", b"box_min_w", "crowd_num_threshold", b"crowd_num_threshold", "det_threshold", b"det_threshold", "faceqa_threshold", b"faceqa_threshold", "match_threshold", b"match_threshold", "pgie_inteval", b"pgie_inteval", "roi", b"roi", "task_type", b"task_type", "window_hit", b"window_hit", "window_len", b"window_len"]) -> None: ...

global___ChanServiceConfig = ChanServiceConfig

@typing_extensions.final
class BindChanTaskReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICE_ID_FIELD_NUMBER: builtins.int
    CHANNEL_ID_FIELD_NUMBER: builtins.int
    CHANNEL_NAME_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    service_id: builtins.int
    channel_id: builtins.int
    channel_name: builtins.str
    config: builtins.str
    """这个json是算法参数，由算法直接解析"""
    def __init__(
        self,
        *,
        service_id: builtins.int = ...,
        channel_id: builtins.int = ...,
        channel_name: builtins.str = ...,
        config: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channel_id", b"channel_id", "channel_name", b"channel_name", "config", b"config", "service_id", b"service_id"]) -> None: ...

global___BindChanTaskReq = BindChanTaskReq

@typing_extensions.final
class UnbindChanTaskReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICE_ID_FIELD_NUMBER: builtins.int
    CHANNEL_ID_FIELD_NUMBER: builtins.int
    service_id: builtins.int
    channel_id: builtins.int
    def __init__(
        self,
        *,
        service_id: builtins.int = ...,
        channel_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channel_id", b"channel_id", "service_id", b"service_id"]) -> None: ...

global___UnbindChanTaskReq = UnbindChanTaskReq

@typing_extensions.final
class Event(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENT_TYPE_FIELD_NUMBER: builtins.int
    JSON_STR_FIELD_NUMBER: builtins.int
    SRCS_FIELD_NUMBER: builtins.int
    TRAINS_FIELD_NUMBER: builtins.int
    ROIS_FIELD_NUMBER: builtins.int
    event_type: global___EventType.ValueType
    json_str: builtins.str
    @property
    def srcs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def trains(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def rois(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        event_type: global___EventType.ValueType = ...,
        json_str: builtins.str = ...,
        srcs: collections.abc.Iterable[builtins.bytes] | None = ...,
        trains: collections.abc.Iterable[builtins.bytes] | None = ...,
        rois: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["event_type", b"event_type", "json_str", b"json_str", "rois", b"rois", "srcs", b"srcs", "trains", b"trains"]) -> None: ...

global___Event = Event
