"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

@Author: AlfredNG
@Date: 2024-05-12 14:54:48
@Description:
@Copyright: Copyright (c) 2024-Present AVCIT
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import proto.alg_core.common_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _GenderType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GenderTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GenderType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GENDER_TYPE_UNKNOWN: _GenderType.ValueType  # 0
    MALE: _GenderType.ValueType  # 1
    FEMALE: _GenderType.ValueType  # 2

class GenderType(_GenderType, metaclass=_GenderTypeEnumTypeWrapper): ...

GENDER_TYPE_UNKNOWN: GenderType.ValueType  # 0
MALE: GenderType.ValueType  # 1
FEMALE: GenderType.ValueType  # 2
global___GenderType = GenderType

class _IsTureFalseType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IsTureFalseTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IsTureFalseType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    FALSE_TRUE_UNKNOWN: _IsTureFalseType.ValueType  # 0
    YES: _IsTureFalseType.ValueType  # 1
    NO: _IsTureFalseType.ValueType  # 2

class IsTureFalseType(_IsTureFalseType, metaclass=_IsTureFalseTypeEnumTypeWrapper): ...

FALSE_TRUE_UNKNOWN: IsTureFalseType.ValueType  # 0
YES: IsTureFalseType.ValueType  # 1
NO: IsTureFalseType.ValueType  # 2
global___IsTureFalseType = IsTureFalseType

class _AgeType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AgeTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AgeType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    AGE_TYPE_UNKNOWN: _AgeType.ValueType  # 0
    KID: _AgeType.ValueType  # 1
    YOUNG: _AgeType.ValueType  # 2
    MIDDLE: _AgeType.ValueType  # 3
    OLD: _AgeType.ValueType  # 4

class AgeType(_AgeType, metaclass=_AgeTypeEnumTypeWrapper):
    """年龄段：未知，孩童、青年、中年、老年"""

AGE_TYPE_UNKNOWN: AgeType.ValueType  # 0
KID: AgeType.ValueType  # 1
YOUNG: AgeType.ValueType  # 2
MIDDLE: AgeType.ValueType  # 3
OLD: AgeType.ValueType  # 4
global___AgeType = AgeType

class _ColorType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ColorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ColorType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    COLOR_TYPE_UNKNOWN: _ColorType.ValueType  # 0
    BLACK: _ColorType.ValueType  # 1
    BROWN: _ColorType.ValueType  # 2
    BLUE: _ColorType.ValueType  # 3
    GREEN: _ColorType.ValueType  # 4
    GRAY: _ColorType.ValueType  # 5
    ORANGE: _ColorType.ValueType  # 6
    PINK: _ColorType.ValueType  # 7
    PURPLE: _ColorType.ValueType  # 8
    RED: _ColorType.ValueType  # 9
    WHITE: _ColorType.ValueType  # 10
    YELLOW: _ColorType.ValueType  # 11

class ColorType(_ColorType, metaclass=_ColorTypeEnumTypeWrapper):
    """颜色：未知，黑，棕，蓝，绿，灰，橙，粉，紫，红，白，黄"""

COLOR_TYPE_UNKNOWN: ColorType.ValueType  # 0
BLACK: ColorType.ValueType  # 1
BROWN: ColorType.ValueType  # 2
BLUE: ColorType.ValueType  # 3
GREEN: ColorType.ValueType  # 4
GRAY: ColorType.ValueType  # 5
ORANGE: ColorType.ValueType  # 6
PINK: ColorType.ValueType  # 7
PURPLE: ColorType.ValueType  # 8
RED: ColorType.ValueType  # 9
WHITE: ColorType.ValueType  # 10
YELLOW: ColorType.ValueType  # 11
global___ColorType = ColorType

class _HairType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _HairTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_HairType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    HAIR_TYPE_UNKNOWN: _HairType.ValueType  # 0
    SHORT: _HairType.ValueType  # 1
    LONG: _HairType.ValueType  # 2
    CURL: _HairType.ValueType  # 3
    BONNET: _HairType.ValueType  # 4
    LONG_CURL: _HairType.ValueType  # 5

class HairType(_HairType, metaclass=_HairTypeEnumTypeWrapper):
    """发型：未知，短发、长发、盘发、光头、中长发"""

HAIR_TYPE_UNKNOWN: HairType.ValueType  # 0
SHORT: HairType.ValueType  # 1
LONG: HairType.ValueType  # 2
CURL: HairType.ValueType  # 3
BONNET: HairType.ValueType  # 4
LONG_CURL: HairType.ValueType  # 5
global___HairType = HairType

class _CarType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CarTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CarType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CAR_TYPE_UNKNOWN: _CarType.ValueType  # 0
    BUS: _CarType.ValueType  # 1
    CAR: _CarType.ValueType  # 2
    TRUCK: _CarType.ValueType  # 3
    BUS_TRUCK: _CarType.ValueType  # 4
    ENGINEER_CAR: _CarType.ValueType  # 5
    TRUCK_SUITCASE: _CarType.ValueType  # 6
    SUV: _CarType.ValueType  # 7
    PASSENGER_Car: _CarType.ValueType  # 8
    BIG_PASSENGER_Car: _CarType.ValueType  # 9
    NORMAL_TRUCK: _CarType.ValueType  # 10
    MINI_TRUCK: _CarType.ValueType  # 11
    MPV: _CarType.ValueType  # 12
    VAN: _CarType.ValueType  # 13
    OFF_ROAD_VEHICLE: _CarType.ValueType  # 14

class CarType(_CarType, metaclass=_CarTypeEnumTypeWrapper):
    """车辆类型：‘未知’，'公交车', '轿车', '大货车', '皮卡车','工程车', '厢式货车',
    'SUV'，客车，大客车，货车，小货车，MPV，面包车，越野车，
    """

CAR_TYPE_UNKNOWN: CarType.ValueType  # 0
BUS: CarType.ValueType  # 1
CAR: CarType.ValueType  # 2
TRUCK: CarType.ValueType  # 3
BUS_TRUCK: CarType.ValueType  # 4
ENGINEER_CAR: CarType.ValueType  # 5
TRUCK_SUITCASE: CarType.ValueType  # 6
SUV: CarType.ValueType  # 7
PASSENGER_Car: CarType.ValueType  # 8
BIG_PASSENGER_Car: CarType.ValueType  # 9
NORMAL_TRUCK: CarType.ValueType  # 10
MINI_TRUCK: CarType.ValueType  # 11
MPV: CarType.ValueType  # 12
VAN: CarType.ValueType  # 13
OFF_ROAD_VEHICLE: CarType.ValueType  # 14
global___CarType = CarType

class _NonVehicleType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _NonVehicleTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_NonVehicleType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NON_VEHICLE_TYPE_UNKNOWN: _NonVehicleType.ValueType  # 0
    MOTOR: _NonVehicleType.ValueType  # 1
    BICYCLE: _NonVehicleType.ValueType  # 2
    TRICYCLE: _NonVehicleType.ValueType  # 3

class NonVehicleType(_NonVehicleType, metaclass=_NonVehicleTypeEnumTypeWrapper):
    """非机动车类型：未知、摩托、自行车、三轮"""

NON_VEHICLE_TYPE_UNKNOWN: NonVehicleType.ValueType  # 0
MOTOR: NonVehicleType.ValueType  # 1
BICYCLE: NonVehicleType.ValueType  # 2
TRICYCLE: NonVehicleType.ValueType  # 3
global___NonVehicleType = NonVehicleType

class _DirectionType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DirectionTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DirectionType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DIRECTION_TYPE_UNKNOWN: _DirectionType.ValueType  # 0
    FRONT: _DirectionType.ValueType  # 1
    SIDE: _DirectionType.ValueType  # 2
    BACK: _DirectionType.ValueType  # 3

class DirectionType(_DirectionType, metaclass=_DirectionTypeEnumTypeWrapper):
    """朝向：未知、正面、侧面、背面"""

DIRECTION_TYPE_UNKNOWN: DirectionType.ValueType  # 0
FRONT: DirectionType.ValueType  # 1
SIDE: DirectionType.ValueType  # 2
BACK: DirectionType.ValueType  # 3
global___DirectionType = DirectionType

class _BackpackType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BackpackTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BackpackType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BACKPACK_TYPE_UNKNOWN: _BackpackType.ValueType  # 0
    DOUBLE_SHOULDER: _BackpackType.ValueType  # 1
    SINGLE_SHOULDER: _BackpackType.ValueType  # 2
    HAND_TIE: _BackpackType.ValueType  # 3
    BackpackType_NONE: _BackpackType.ValueType  # 4

class BackpackType(_BackpackType, metaclass=_BackpackTypeEnumTypeWrapper):
    """背包类型：未知、双肩包、单肩包、手提包、无"""

BACKPACK_TYPE_UNKNOWN: BackpackType.ValueType  # 0
DOUBLE_SHOULDER: BackpackType.ValueType  # 1
SINGLE_SHOULDER: BackpackType.ValueType  # 2
HAND_TIE: BackpackType.ValueType  # 3
BackpackType_NONE: BackpackType.ValueType  # 4
global___BackpackType = BackpackType

class _UpperType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UpperTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UpperType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UPPER_TYPE_UNKNOWN: _UpperType.ValueType  # 0
    SHORT_SLEEVE: _UpperType.ValueType  # 1
    LONG_SLEEVE: _UpperType.ValueType  # 2

class UpperType(_UpperType, metaclass=_UpperTypeEnumTypeWrapper):
    """上身类型：未知、短袖、长袖"""

UPPER_TYPE_UNKNOWN: UpperType.ValueType  # 0
SHORT_SLEEVE: UpperType.ValueType  # 1
LONG_SLEEVE: UpperType.ValueType  # 2
global___UpperType = UpperType

class _UpperTexture:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UpperTextureEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UpperTexture.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UPPER_TEXTURE_UNKNOWN: _UpperTexture.ValueType  # 0
    GRID: _UpperTexture.ValueType  # 1
    fLORAL: _UpperTexture.ValueType  # 2
    PURE: _UpperTexture.ValueType  # 3
    STRIPED: _UpperTexture.ValueType  # 4

class UpperTexture(_UpperTexture, metaclass=_UpperTextureEnumTypeWrapper):
    """上衣纹理：未知、格子、碎花、纯色、条纹"""

UPPER_TEXTURE_UNKNOWN: UpperTexture.ValueType  # 0
GRID: UpperTexture.ValueType  # 1
fLORAL: UpperTexture.ValueType  # 2
PURE: UpperTexture.ValueType  # 3
STRIPED: UpperTexture.ValueType  # 4
global___UpperTexture = UpperTexture

class _ShoeType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ShoeTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ShoeType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SHOE_TYPE_UNKNOWN: _ShoeType.ValueType  # 0
    LEATHER: _ShoeType.ValueType  # 1
    SANDAL: _ShoeType.ValueType  # 2
    CASUAL: _ShoeType.ValueType  # 3
    HIGH_TALL: _ShoeType.ValueType  # 4

class ShoeType(_ShoeType, metaclass=_ShoeTypeEnumTypeWrapper):
    """鞋类型：未知、皮鞋、凉鞋、休闲鞋、高筒靴"""

SHOE_TYPE_UNKNOWN: ShoeType.ValueType  # 0
LEATHER: ShoeType.ValueType  # 1
SANDAL: ShoeType.ValueType  # 2
CASUAL: ShoeType.ValueType  # 3
HIGH_TALL: ShoeType.ValueType  # 4
global___ShoeType = ShoeType

class _LowerType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LowerTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LowerType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LOWER_TYPE_UNKNOWN: _LowerType.ValueType  # 0
    SHORT_PANTS: _LowerType.ValueType  # 1
    LONG_PANTS: _LowerType.ValueType  # 2

class LowerType(_LowerType, metaclass=_LowerTypeEnumTypeWrapper):
    """下身类型：未知、短裤、长裤"""

LOWER_TYPE_UNKNOWN: LowerType.ValueType  # 0
SHORT_PANTS: LowerType.ValueType  # 1
LONG_PANTS: LowerType.ValueType  # 2
global___LowerType = LowerType

class _Pictureformat:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PictureformatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Pictureformat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PICTURE_FORMAT_UNKNOW: _Pictureformat.ValueType  # 0
    JPEG: _Pictureformat.ValueType  # 1
    PNG: _Pictureformat.ValueType  # 2
    GIF: _Pictureformat.ValueType  # 3
    BMP: _Pictureformat.ValueType  # 4

class Pictureformat(_Pictureformat, metaclass=_PictureformatEnumTypeWrapper): ...

PICTURE_FORMAT_UNKNOW: Pictureformat.ValueType  # 0
JPEG: Pictureformat.ValueType  # 1
PNG: Pictureformat.ValueType  # 2
GIF: Pictureformat.ValueType  # 3
BMP: Pictureformat.ValueType  # 4
global___Pictureformat = Pictureformat

class _PictureType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PictureTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PictureType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PICTURE_TYPE_UNKNOW: _PictureType.ValueType  # 0
    PICTURE_TYPE_FACE: _PictureType.ValueType  # 1
    """人脸图像"""
    PICTURE_TYPE_PERSON: _PictureType.ValueType  # 2
    """行人图像"""
    PICTURE_TYPE_NON_VECHICLE: _PictureType.ValueType  # 3
    """驾驶非机动车图像"""
    PICTURE_TYPE_VECHICLE: _PictureType.ValueType  # 4
    """机动车图像"""
    PICTURE_TYPE_BIKE: _PictureType.ValueType  # 5
    """自行车"""
    PICTURE_TYPE_TRICYCLE: _PictureType.ValueType  # 6
    """三轮车"""
    PICTURE_TYPE_EBIKE_LADDER: _PictureType.ValueType  # 7
    """电动车进楼梯"""
    PICTURE_TYPE_DOG_WALK: _PictureType.ValueType  # 8
    """遛狗不牵绳"""
    PICTURE_TYPE_NONCAR_OCCUPY: _PictureType.ValueType  # 9
    """非机动车占道"""
    PICTURE_TYPE_SHIP_OBJCAP: _PictureType.ValueType  # 10
    """船只图像"""
    PICTURE_TYPE_RUBBISH_HEAP: _PictureType.ValueType  # 11
    """垃圾堆积"""
    PICTURE_TYPE_RUBBISH_OVERFLOW: _PictureType.ValueType  # 12
    """垃圾溢出"""
    PICTURE_TYPE_PERSON_WANDER: _PictureType.ValueType  # 13
    """徘徊检测"""
    PICTURE_TYPE_RIDE: _PictureType.ValueType  # 14
    """骑行检测"""
    PICTURE_TYPE_CROWD_DET: _PictureType.ValueType  # 15
    """人群聚集检测"""
    PICTURE_TYPE_FALLDOWN_DET: _PictureType.ValueType  # 16
    """跌倒检测"""
    PICTURE_TYPE_SMOKE_DET: _PictureType.ValueType  # 17
    """浓烟检测"""
    PICTURE_TYPE_FIRE_DET: _PictureType.ValueType  # 18
    """明火检测"""
    PICTURE_TYPE_HELMET_DET_NOTRACK: _PictureType.ValueType  # 19
    """未佩戴安全帽检测"""
    PICTURE_TYPE_REFLECT_DET_NOTRACK: _PictureType.ValueType  # 20
    """未穿戴反光衣检测"""
    PICTURE_TYPE_PERSON_BREAKIN_NOTRACK: _PictureType.ValueType  # 21
    """区域入侵检测"""
    PICTURE_TYPE_FACEMASK_DET_NOTRACK: _PictureType.ValueType  # 22
    """未佩戴口罩检测"""
    PICTURE_TYPE_VEST_DET_NOTRACK: _PictureType.ValueType  # 23
    """未穿工衣检测"""

class PictureType(_PictureType, metaclass=_PictureTypeEnumTypeWrapper): ...

PICTURE_TYPE_UNKNOW: PictureType.ValueType  # 0
PICTURE_TYPE_FACE: PictureType.ValueType  # 1
"""人脸图像"""
PICTURE_TYPE_PERSON: PictureType.ValueType  # 2
"""行人图像"""
PICTURE_TYPE_NON_VECHICLE: PictureType.ValueType  # 3
"""驾驶非机动车图像"""
PICTURE_TYPE_VECHICLE: PictureType.ValueType  # 4
"""机动车图像"""
PICTURE_TYPE_BIKE: PictureType.ValueType  # 5
"""自行车"""
PICTURE_TYPE_TRICYCLE: PictureType.ValueType  # 6
"""三轮车"""
PICTURE_TYPE_EBIKE_LADDER: PictureType.ValueType  # 7
"""电动车进楼梯"""
PICTURE_TYPE_DOG_WALK: PictureType.ValueType  # 8
"""遛狗不牵绳"""
PICTURE_TYPE_NONCAR_OCCUPY: PictureType.ValueType  # 9
"""非机动车占道"""
PICTURE_TYPE_SHIP_OBJCAP: PictureType.ValueType  # 10
"""船只图像"""
PICTURE_TYPE_RUBBISH_HEAP: PictureType.ValueType  # 11
"""垃圾堆积"""
PICTURE_TYPE_RUBBISH_OVERFLOW: PictureType.ValueType  # 12
"""垃圾溢出"""
PICTURE_TYPE_PERSON_WANDER: PictureType.ValueType  # 13
"""徘徊检测"""
PICTURE_TYPE_RIDE: PictureType.ValueType  # 14
"""骑行检测"""
PICTURE_TYPE_CROWD_DET: PictureType.ValueType  # 15
"""人群聚集检测"""
PICTURE_TYPE_FALLDOWN_DET: PictureType.ValueType  # 16
"""跌倒检测"""
PICTURE_TYPE_SMOKE_DET: PictureType.ValueType  # 17
"""浓烟检测"""
PICTURE_TYPE_FIRE_DET: PictureType.ValueType  # 18
"""明火检测"""
PICTURE_TYPE_HELMET_DET_NOTRACK: PictureType.ValueType  # 19
"""未佩戴安全帽检测"""
PICTURE_TYPE_REFLECT_DET_NOTRACK: PictureType.ValueType  # 20
"""未穿戴反光衣检测"""
PICTURE_TYPE_PERSON_BREAKIN_NOTRACK: PictureType.ValueType  # 21
"""区域入侵检测"""
PICTURE_TYPE_FACEMASK_DET_NOTRACK: PictureType.ValueType  # 22
"""未佩戴口罩检测"""
PICTURE_TYPE_VEST_DET_NOTRACK: PictureType.ValueType  # 23
"""未穿工衣检测"""
global___PictureType = PictureType

@typing_extensions.final
class FaceParam(google.protobuf.message.Message):
    """所有int32类型均从1开始递增，对应相应中文类型，例如黑，棕，蓝，绿，灰，橙，粉，紫，红，白，黄，就是1,2,3,4,5,6,
    所有int32类型对应的是否均为0：未知，1是，2否
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    GENDER_FIELD_NUMBER: builtins.int
    MASK_FIELD_NUMBER: builtins.int
    GLASSES_FIELD_NUMBER: builtins.int
    id: builtins.int
    age: global___AgeType.ValueType
    """年龄段：孩童、青年、中年、老年"""
    gender: global___GenderType.ValueType
    """性别:男、女"""
    mask: global___IsTureFalseType.ValueType
    """是否戴口罩"""
    glasses: global___IsTureFalseType.ValueType
    """是否戴眼镜"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        age: global___AgeType.ValueType = ...,
        gender: global___GenderType.ValueType = ...,
        mask: global___IsTureFalseType.ValueType = ...,
        glasses: global___IsTureFalseType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["age", b"age", "gender", b"gender", "glasses", b"glasses", "id", b"id", "mask", b"mask"]) -> None: ...

global___FaceParam = FaceParam

@typing_extensions.final
class PersonParam(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    GENDER_FIELD_NUMBER: builtins.int
    UPPER_TYPE_FIELD_NUMBER: builtins.int
    UPPER_COLOR_FIELD_NUMBER: builtins.int
    LOWER_TYPE_FIELD_NUMBER: builtins.int
    LOWER_COLOR_FIELD_NUMBER: builtins.int
    SKIRT_FIELD_NUMBER: builtins.int
    HAT_FIELD_NUMBER: builtins.int
    MASK_FIELD_NUMBER: builtins.int
    BACKPACK_FIELD_NUMBER: builtins.int
    RIDING_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    HAIR_FIELD_NUMBER: builtins.int
    UPPER_TEXTURE_FIELD_NUMBER: builtins.int
    SHOE_TYPE_FIELD_NUMBER: builtins.int
    SHOE_COLOR_FIELD_NUMBER: builtins.int
    id: builtins.int
    age: global___AgeType.ValueType
    """年龄段：孩童、青年、中年、老年"""
    gender: global___GenderType.ValueType
    """性别:男、女"""
    upper_type: global___UpperType.ValueType
    """上身类型：短袖、长袖"""
    upper_color: global___ColorType.ValueType
    """上身颜色：黑，棕，蓝，绿，灰，橙，粉，紫，红，白，黄"""
    lower_type: global___LowerType.ValueType
    """下身类型：短裤、长裤"""
    lower_color: global___ColorType.ValueType
    """下身颜色：黑，棕，蓝，绿，灰，橙，粉，紫，红，白，黄"""
    skirt: global___IsTureFalseType.ValueType
    """是否穿裙子"""
    hat: global___IsTureFalseType.ValueType
    """是否戴帽子"""
    mask: global___IsTureFalseType.ValueType
    """是否戴口罩"""
    backpack: global___BackpackType.ValueType
    """背包类型：双肩包、单肩包、手提包、无"""
    riding: global___IsTureFalseType.ValueType
    """是否骑自行车"""
    direction: global___DirectionType.ValueType
    """朝向：正面、侧面、背面"""
    hair: global___HairType.ValueType
    """发型：短发、长发、盘发、光头、中长发"""
    upper_texture: global___UpperTexture.ValueType
    """上衣纹理：格子、碎花、纯色、条纹"""
    shoe_type: global___ShoeType.ValueType
    """鞋类型：皮鞋、凉鞋、休闲鞋、高筒靴"""
    shoe_color: global___ColorType.ValueType
    """鞋颜色：黑，棕，蓝，绿，灰，橙，粉，紫，红，白，黄"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        age: global___AgeType.ValueType = ...,
        gender: global___GenderType.ValueType = ...,
        upper_type: global___UpperType.ValueType = ...,
        upper_color: global___ColorType.ValueType = ...,
        lower_type: global___LowerType.ValueType = ...,
        lower_color: global___ColorType.ValueType = ...,
        skirt: global___IsTureFalseType.ValueType = ...,
        hat: global___IsTureFalseType.ValueType = ...,
        mask: global___IsTureFalseType.ValueType = ...,
        backpack: global___BackpackType.ValueType = ...,
        riding: global___IsTureFalseType.ValueType = ...,
        direction: global___DirectionType.ValueType = ...,
        hair: global___HairType.ValueType = ...,
        upper_texture: global___UpperTexture.ValueType = ...,
        shoe_type: global___ShoeType.ValueType = ...,
        shoe_color: global___ColorType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["age", b"age", "backpack", b"backpack", "direction", b"direction", "gender", b"gender", "hair", b"hair", "hat", b"hat", "id", b"id", "lower_color", b"lower_color", "lower_type", b"lower_type", "mask", b"mask", "riding", b"riding", "shoe_color", b"shoe_color", "shoe_type", b"shoe_type", "skirt", b"skirt", "upper_color", b"upper_color", "upper_texture", b"upper_texture", "upper_type", b"upper_type"]) -> None: ...

global___PersonParam = PersonParam

@typing_extensions.final
class CarParam(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    PLATE_TYPE_FIELD_NUMBER: builtins.int
    PLATE_LICENSE_FIELD_NUMBER: builtins.int
    PLATE_COLOR_FIELD_NUMBER: builtins.int
    CAR_TYPE_FIELD_NUMBER: builtins.int
    CAR_BRAND_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    CAR_COLOR_FIELD_NUMBER: builtins.int
    id: builtins.int
    plate_type: builtins.int
    """车牌类型：未实现，先占位"""
    plate_license: builtins.str
    """车牌号"""
    plate_color: global___ColorType.ValueType
    """车牌颜色：蓝、黄、白、黑、绿"""
    car_type: global___CarType.ValueType
    """车辆类型：'公交车', '轿车', '大货车', '皮卡车',"""
    car_brand: builtins.str
    """'工程车', '厢式货车', 'SUV'
    车辆品牌：未实现，先占位
    """
    direction: global___DirectionType.ValueType
    """车辆朝向：正面、侧面、背面"""
    car_color: global___ColorType.ValueType
    """车辆颜色：'黄色', '白色', '红色', '蓝色', '绿色',"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        plate_type: builtins.int = ...,
        plate_license: builtins.str = ...,
        plate_color: global___ColorType.ValueType = ...,
        car_type: global___CarType.ValueType = ...,
        car_brand: builtins.str = ...,
        direction: global___DirectionType.ValueType = ...,
        car_color: global___ColorType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["car_brand", b"car_brand", "car_color", b"car_color", "car_type", b"car_type", "direction", b"direction", "id", b"id", "plate_color", b"plate_color", "plate_license", b"plate_license", "plate_type", b"plate_type"]) -> None: ...

global___CarParam = CarParam

@typing_extensions.final
class NonVehicleParam(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    HELMET_FIELD_NUMBER: builtins.int
    PEOPEL_NUMBER_FIELD_NUMBER: builtins.int
    GENDER_FIELD_NUMBER: builtins.int
    NONVEHICLE_TYPE_FIELD_NUMBER: builtins.int
    UPPER_COLOR_FIELD_NUMBER: builtins.int
    UPPER_TYPE_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    NONVEHICLE_PLATE_FIELD_NUMBER: builtins.int
    NONVEHICLE_COLOR_FIELD_NUMBER: builtins.int
    id: builtins.int
    helmet: global___IsTureFalseType.ValueType
    """是否戴头盔"""
    peopel_number: builtins.int
    """载人数"""
    gender: global___GenderType.ValueType
    """性别"""
    nonvehicle_type: global___NonVehicleType.ValueType
    """非机动车类型：摩托、自行车、三轮"""
    upper_color: global___ColorType.ValueType
    """上身颜色：黑，棕，蓝，绿，灰，橙，粉，紫，红，白，黄"""
    upper_type: global___UpperType.ValueType
    """上身类型：短袖、长袖"""
    age: global___AgeType.ValueType
    """年龄段：孩童、青年、老年"""
    nonvehicle_plate: builtins.str
    """非机动车车牌号"""
    nonvehicle_color: global___ColorType.ValueType
    """非机动车颜色:黑，棕，蓝，绿，灰，橙，粉，紫，红，白，黄"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        helmet: global___IsTureFalseType.ValueType = ...,
        peopel_number: builtins.int = ...,
        gender: global___GenderType.ValueType = ...,
        nonvehicle_type: global___NonVehicleType.ValueType = ...,
        upper_color: global___ColorType.ValueType = ...,
        upper_type: global___UpperType.ValueType = ...,
        age: global___AgeType.ValueType = ...,
        nonvehicle_plate: builtins.str = ...,
        nonvehicle_color: global___ColorType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["age", b"age", "gender", b"gender", "helmet", b"helmet", "id", b"id", "nonvehicle_color", b"nonvehicle_color", "nonvehicle_plate", b"nonvehicle_plate", "nonvehicle_type", b"nonvehicle_type", "peopel_number", b"peopel_number", "upper_color", b"upper_color", "upper_type", b"upper_type"]) -> None: ...

global___NonVehicleParam = NonVehicleParam

@typing_extensions.final
class EbikeLadderParam(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    BBOX_FIELD_NUMBER: builtins.int
    id: builtins.int
    @property
    def bbox(self) -> proto.alg_core.common_pb2.Rectangle: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        bbox: proto.alg_core.common_pb2.Rectangle | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bbox", b"bbox"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bbox", b"bbox", "id", b"id"]) -> None: ...

global___EbikeLadderParam = EbikeLadderParam

@typing_extensions.final
class PictureData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    width: builtins.int
    height: builtins.int
    format: global___Pictureformat.ValueType
    data: builtins.bytes
    def __init__(
        self,
        *,
        width: builtins.int = ...,
        height: builtins.int = ...,
        format: global___Pictureformat.ValueType = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "format", b"format", "height", b"height", "width", b"width"]) -> None: ...

global___PictureData = PictureData

@typing_extensions.final
class UploadPictureReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    SRC_FIELD_NUMBER: builtins.int
    ROI_FIELD_NUMBER: builtins.int
    TRAIN_FIELD_NUMBER: builtins.int
    CHANNEL_ID_FIELD_NUMBER: builtins.int
    CHANNEL_NAME_FIELD_NUMBER: builtins.int
    TRAIN_JSON_STR_FIELD_NUMBER: builtins.int
    CHANNEL_ZONE_FIELD_NUMBER: builtins.int
    PERSON_FIELD_NUMBER: builtins.int
    FACE_FIELD_NUMBER: builtins.int
    CAR_FIELD_NUMBER: builtins.int
    NONVEHICLE_FIELD_NUMBER: builtins.int
    PARAM_STR_FIELD_NUMBER: builtins.int
    DEVICE_NAME_FIELD_NUMBER: builtins.int
    DEVICE_ID_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    SERIAL_FIELD_NUMBER: builtins.int
    id: builtins.int
    type: global___PictureType.ValueType
    src: builtins.bytes
    roi: builtins.bytes
    train: builtins.bytes
    channel_id: builtins.int
    channel_name: builtins.str
    train_json_str: builtins.str
    channel_zone: builtins.str
    @property
    def person(self) -> global___PersonParam: ...
    @property
    def face(self) -> global___FaceParam: ...
    @property
    def car(self) -> global___CarParam: ...
    @property
    def nonvehicle(self) -> global___NonVehicleParam: ...
    param_str: builtins.str
    device_name: builtins.str
    device_id: builtins.int
    url: builtins.str
    """图片的通道地址"""
    serial: builtins.str
    """设备序列号"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        type: global___PictureType.ValueType = ...,
        src: builtins.bytes = ...,
        roi: builtins.bytes = ...,
        train: builtins.bytes = ...,
        channel_id: builtins.int = ...,
        channel_name: builtins.str = ...,
        train_json_str: builtins.str = ...,
        channel_zone: builtins.str = ...,
        person: global___PersonParam | None = ...,
        face: global___FaceParam | None = ...,
        car: global___CarParam | None = ...,
        nonvehicle: global___NonVehicleParam | None = ...,
        param_str: builtins.str = ...,
        device_name: builtins.str = ...,
        device_id: builtins.int = ...,
        url: builtins.str = ...,
        serial: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["car", b"car", "face", b"face", "nonvehicle", b"nonvehicle", "param", b"param", "person", b"person"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["car", b"car", "channel_id", b"channel_id", "channel_name", b"channel_name", "channel_zone", b"channel_zone", "device_id", b"device_id", "device_name", b"device_name", "face", b"face", "id", b"id", "nonvehicle", b"nonvehicle", "param", b"param", "param_str", b"param_str", "person", b"person", "roi", b"roi", "serial", b"serial", "src", b"src", "train", b"train", "train_json_str", b"train_json_str", "type", b"type", "url", b"url"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["param", b"param"]) -> typing_extensions.Literal["person", "face", "car", "nonvehicle"] | None: ...

global___UploadPictureReq = UploadPictureReq

@typing_extensions.final
class ClipPictureReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    DEVICE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    BASE64_FIELD_NUMBER: builtins.int
    BBOX_FIELD_NUMBER: builtins.int
    BASE64_ROI_FIELD_NUMBER: builtins.int
    id: builtins.int
    device: builtins.str
    """摄像头名称"""
    type: global___PictureType.ValueType
    """采集目标的类型：人脸，行人，非机动车，机动车，自行车，三轮车"""
    time: builtins.str
    """采集时间"""
    base64: builtins.bytes
    """采集设备的base64图像数据"""
    @property
    def bbox(self) -> proto.alg_core.common_pb2.Rectangle:
        """目标的坐标"""
    base64_roi: builtins.bytes
    """采集设备的base64图像ROI数据"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        device: builtins.str = ...,
        type: global___PictureType.ValueType = ...,
        time: builtins.str = ...,
        base64: builtins.bytes = ...,
        bbox: proto.alg_core.common_pb2.Rectangle | None = ...,
        base64_roi: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bbox", b"bbox"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["base64", b"base64", "base64_roi", b"base64_roi", "bbox", b"bbox", "device", b"device", "id", b"id", "time", b"time", "type", b"type"]) -> None: ...

global___ClipPictureReq = ClipPictureReq

@typing_extensions.final
class ClipPictureRes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    PERSON_FIELD_NUMBER: builtins.int
    FACE_FIELD_NUMBER: builtins.int
    CAR_FIELD_NUMBER: builtins.int
    NONVEHICLE_FIELD_NUMBER: builtins.int
    id: builtins.int
    code: builtins.int
    """识别码 0:成功,负数是失败"""
    message: builtins.str
    """错误信息"""
    type: global___PictureType.ValueType
    """目标的类型：人脸，行人，非机动车，机动车，自行车，三轮车"""
    @property
    def person(self) -> global___PersonParam: ...
    @property
    def face(self) -> global___FaceParam: ...
    @property
    def car(self) -> global___CarParam: ...
    @property
    def nonvehicle(self) -> global___NonVehicleParam: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        code: builtins.int = ...,
        message: builtins.str = ...,
        type: global___PictureType.ValueType = ...,
        person: global___PersonParam | None = ...,
        face: global___FaceParam | None = ...,
        car: global___CarParam | None = ...,
        nonvehicle: global___NonVehicleParam | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["car", b"car", "face", b"face", "nonvehicle", b"nonvehicle", "param", b"param", "person", b"person"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["car", b"car", "code", b"code", "face", b"face", "id", b"id", "message", b"message", "nonvehicle", b"nonvehicle", "param", b"param", "person", b"person", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["param", b"param"]) -> typing_extensions.Literal["person", "face", "car", "nonvehicle"] | None: ...

global___ClipPictureRes = ClipPictureRes
