# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.alg_core import picture_pb2 as proto_dot_alg__core_dot_picture__pb2


class PictureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadPicture = channel.unary_unary(
                '/alg_core.PictureService/UploadPicture',
                request_serializer=proto_dot_alg__core_dot_picture__pb2.UploadPictureReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ClipPicture = channel.unary_unary(
                '/alg_core.PictureService/ClipPicture',
                request_serializer=proto_dot_alg__core_dot_picture__pb2.ClipPictureReq.SerializeToString,
                response_deserializer=proto_dot_alg__core_dot_picture__pb2.ClipPictureRes.FromString,
                )


class PictureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadPicture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClipPicture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PictureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadPicture': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPicture,
                    request_deserializer=proto_dot_alg__core_dot_picture__pb2.UploadPictureReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ClipPicture': grpc.unary_unary_rpc_method_handler(
                    servicer.ClipPicture,
                    request_deserializer=proto_dot_alg__core_dot_picture__pb2.ClipPictureReq.FromString,
                    response_serializer=proto_dot_alg__core_dot_picture__pb2.ClipPictureRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alg_core.PictureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PictureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadPicture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alg_core.PictureService/UploadPicture',
            proto_dot_alg__core_dot_picture__pb2.UploadPictureReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClipPicture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alg_core.PictureService/ClipPicture',
            proto_dot_alg__core_dot_picture__pb2.ClipPictureReq.SerializeToString,
            proto_dot_alg__core_dot_picture__pb2.ClipPictureRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
